[package]
name = "fluxdb"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
bincode = "1"
tokio = { version = "1.48.0", features = ["full"] }
